# Generated by Django 5.2.2 on 2025-06-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=250)),
                ('sells_point', models.CharField(max_length=250)),
                ('target', models.CharField(max_length=250)),
            ],
        ),
    ]
